// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        //kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyC8jqdtTywyuOeE8jXIuCnUzidNp39qgGA',
  //   appId: '1:588960304455:web:58fb54259f2856af191062',
  //   messagingSenderId: '588960304455',
  //   projectId: 'chulpaninsurance',
  //   authDomain: 'chulpaninsurance.firebaseapp.com',
  //   storageBucket: 'chulpaninsurance.appspot.com',
  //   measurementId: 'G-KTC9EENGES',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKa1BkwQysUZiOVysXXC2uQVFVHBSGJA',
    appId: '1:588960304455:android:e3865bac17f0baf4191062',
    messagingSenderId: '588960304455',
    projectId: 'chulpaninsurance',
    storageBucket: 'chulpaninsurance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDz-_IcGd0y2J3ep81pUz2Pm9K6Lf8g4',
    appId: '1:588960304455:ios:c4ea2f06f93e6ad4191062',
    messagingSenderId: '588960304455',
    projectId: 'chulpaninsurance',
    storageBucket: 'chulpaninsurance.appspot.com',
    iosBundleId: 'ru.chulpan.chulpanMobile',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAqDz-_IcGd0y2J3ep81pUz2Pm9K6Lf8g4',
  //   appId: '1:588960304455:ios:c4ea2f06f93e6ad4191062',
  //   messagingSenderId: '588960304455',
  //   projectId: 'chulpaninsurance',
  //   storageBucket: 'chulpaninsurance.appspot.com',
  //   iosBundleId: 'ru.chulpan.chulpanMobile',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyC8jqdtTywyuOeE8jXIuCnUzidNp39qgGA',
  //   appId: '1:588960304455:web:3be1f6fa5a1f7b52191062',
  //   messagingSenderId: '588960304455',
  //   projectId: 'chulpaninsurance',
  //   authDomain: 'chulpaninsurance.firebaseapp.com',
  //   storageBucket: 'chulpaninsurance.appspot.com',
  //   measurementId: 'G-346N3HZ939',
  // );
}
