// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        //kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '239ASFSDKIzaSyALMFDSF23ZiOVysXXC2uQVFVHBSGJ232D',
    appId: '1:588960304455:android:e3865bac17f0baf4191062',
    messagingSenderId: '588960304455',
    projectId: 'example',
    storageBucket: 'example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '239ASFSDKIzaSyALMFDSF23ZiOVysXXC2uQVFVHBSGJ232D',
    appId: '1:588960304455:android:e3865bac17f0baf4191062',
    messagingSenderId: '588960304455',
    projectId: 'example',
    storageBucket: 'example.appspot.com',
  );

}
